[custom.all.streams]
type   = "local"
path   = "."
ipkg   = "streams.ipkg"
test   = "test/test.ipkg"

[custom.all.streams-posix]
type   = "local"
path   = "posix"
ipkg   = "streams-posix.ipkg"

[custom.all.streams-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.streams-profile]
type   = "local"
path   = "profile"
ipkg   = "streams-profile.ipkg"

[custom.all.elin]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elin"
commit = "latest:main"
ipkg   = "elin.ipkg"

[custom.all.ref1]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-ref1"
commit = "latest:main"
ipkg   = "ref1.ipkg"

[custom.all.posix]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-linux"
commit = "latest:main"
ipkg   = "posix/posix.ipkg"

[custom.all.linux]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-linux"
commit = "latest:main"
ipkg   = "linux/linux.ipkg"

[custom.all.bytestring]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-bytestring"
commit = "latest:main"
ipkg   = "bytestring.ipkg"

[custom.all.async]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-async"
commit = "latest:main"
ipkg   = "async.ipkg"

[custom.all.async-spec]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-async"
commit = "latest:main"
ipkg   = "async-spec/async-spec.ipkg"

[custom.all.async-posix]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-async"
commit = "latest:main"
ipkg   = "async-posix/async-posix.ipkg"

[custom.all.async-epoll]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-async"
commit = "latest:main"
ipkg   = "async-epoll/async-epoll.ipkg"
